name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: springbootreactjs
  DOCKER_TAG: 0.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd BackEnd_RestAPI
          mvn clean package -Dmaven.test.skip=true

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{secrets.DOCKER_USERNAME}}/$DOCKER_IMAGE
          tags: $DOCKER_TAG
          registry: docker.io
          dockerfile: BackEnd_RestAPI/Dockerfile  # Dockerfile 경로를 절대 경로로 지정
          directory: BackEnd_RestAPI  # Docker 빌드 컨텍스트를 BackEnd_RestAPI 디렉토리로 지정
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}